travis:
  secure:
    BINSTAR_TOKEN: rsLd88gFc3z9pSGjvYv3SyT2VB0FgG6Hi7CqGWvupQt9FeIZYtPBzO5eSChKfcVydclyepn/W+KhGw+B1gG6XAF28sIHQzIOsURFX9pNH0kvBOB1UypZB0gNbNNmR0zCcX1nIuSwipikyp5hCVpXrALEKRDwp3IYUN/H3iIR/+fESW8LFFn6rJ490Rll40ZV/zalbVX3PiOi79/uLVRLWp2VVVEYnoF8yxdgTF9k1aquGBxB5vuiZkmYwqIhjdA1xqJfIoxHtB4iUT4QaDe22nt0GCASzdruBUeMbcZfLxENTo6A9/3eP26wTCVAWoBvDt8jFT+Yrjb1YfiMkkNzjK+14qFH5ntt8+9JgVciescOHrxaoghJURq6DlEGSNZN2A70gW8UcqV4iXTiVh2I1XpkD+H5eNK2+ts5AqfNUnxENg6rvGI/s9iWG3d+ZL4VPx8XDheU6vHXKK326hIUYKhJTxcIlxYdzWZofbLFFTqHNZ23vM9XmX5N1sSOdKlwpkrDJpzVLlWHp44dU8vsIIowyXaYDq8+ReYJllX48NvkGCZ56uzZkscmg+3RN6oEqIL5YBLTF/bZAz3+Z/3xr3IalXrVfxpSAG1R0nspQRKFjOsIH5LLQjKkWYtFJcMQi29JB4jHMczcCbnVJeBAdIuW48zURwsQVdY3KdRLRB0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
