travis:
  secure:
    BINSTAR_TOKEN: HxsQVO8CCBIKm+0WQvwu2rCdNkhvhZTr6EjV4oO4y99fvWDzoy4tVVMjvQC+dGpL1e3C5zG6n+L/k3ZfBJ3Wv/yrW6Xq79BDEWZ50SHR71YBGrR6ZCm6X2Vhrw5RCUTo+hn4xBwwmKHEOUiHLmSZsyWokorWWRB+wuRRn3pXkcz6dxU9eN4Zwar+Ga+T+sYAbouxIaLZqCwG0LFA+m8pFi2KyYLYgAeWRuzzrSHY0AIiDESx0wqshV8S0bIyfL8plwMyI9VVaZGce9bMdKnJWW/II9BqpR81sGI86z+z4SQH0pN+gUzrG/GDpnM07gsM/7BYu15Xy3lsQ3D/kOr2qrgPp8BovJdbXwHyd8JaiVb3dccG/TVfB4KElH0LrAUkzVPFy/FtBCPfTTz6VyDOk/uuMrJDn7suI7ndBsEVmOjFblcwiuR+jVnapiUL6ldnx3JVesUtxRX2LSyN2l+E8ZKpv7SvXrB82FvxzAdAFUhwsN/VKm8f+2PEd5/VA4ml1requKDn1zlajkqcANZR97+EYUbfeIDYPjwSAyANaAzLqvSovCO1+F9Y+d6qAFL8Wt7C9xx5grcv5WAJum0cmryUTVUAlsasJU364wPoeo03Tu+ZlI1S7t51gC3OknDEH3XOJK7gVUL9Yzd7HnZkH5K+D9oNTsBXbSPtRbnxGMk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
